# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField()),
                ('win_loss', models.BooleanField()),
                ('end_golddifference', models.IntegerField()),
                ('biggest_deficit', models.IntegerField()),
                ('biggest_advantage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=100)),
                ('account_id', models.BigIntegerField()),
                ('profile_icon_id', models.IntegerField()),
                ('summoner_level', models.BigIntegerField()),
                ('last_change', models.DateTimeField(verbose_name='date entry changed')),
            ],
        ),
        migrations.CreateModel(
            name='SummonerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadprofile.MatchSummary')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadprofile.Summoner')),
            ],
        ),
    ]
