# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summonermatch',
            old_name='team_id',
            new_name='participant_id',
        ),
        migrations.AlterField(
            model_name='matchsummary',
            name='biggest_advantage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchsummary',
            name='biggest_deficit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
