# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadprofile', '0002_auto_20170524_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonermatch',
            name='match',
        ),
        migrations.RemoveField(
            model_name='summonermatch',
            name='summoner',
        ),
        migrations.RemoveField(
            model_name='matchsummary',
            name='biggest_advantage',
        ),
        migrations.RemoveField(
            model_name='matchsummary',
            name='biggest_deficit',
        ),
        migrations.RemoveField(
            model_name='matchsummary',
            name='end_golddifference',
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='cs_average10',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='gpm_average10',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='summoner',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='loadprofile.Summoner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='xpm_average10',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SummonerMatch',
        ),
    ]
