# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadprofile', '0003_auto_20170524_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsummary',
            name='game_date',
            field=models.CharField(default='ho', max_length=100),
            preserve_default=False,
        ),
    ]
