# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadprofile', '0005_auto_20170526_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsummary',
            name='assists',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='champion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='deaths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='endCS',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='endGold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='items',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='kills',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='lvl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='role',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='spell1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsummary',
            name='spell2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
